### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by willin** [moscajs/aedes#144]
```
/Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes/lib/handlers/subscribe.js:146
    done()
    ^

TypeError: done is not a function
    at SubscribeState.completeSubscribe (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes/lib/handlers/subscribe.js:146:5)
    at ResultsHolder.release (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/fastparallel/parallel.js:183:12)
    at SubscribeState.SingleCaller.release (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/fastparallel/parallel.js:157:17)
    at work (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/fastfall/fall.js:121:25)
    at SubscribeState.subTopic (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes/lib/handlers/subscribe.js:86:12)
    at work (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/fastfall/fall.js:105:23)
    at /Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes/lib/handlers/subscribe.js:79:5
    at MemoryPersistence.addSubscriptions (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes-persistence/persistence.js:112:3)
    at SubscribeState.storeSubscriptions (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/aedes/lib/handlers/subscribe.js:78:9)
    at work (/Users/willin/Desktop/iothub-mqtt-demo/node_modules/fastfall/fall.js:105:23)
```

**Comment by mcollina** [comment]
Can you please write down instructions to reproduce?

**Comment by deluxeroot** [comment]
I am getting this error when I try:
I have a mqtt clinet and I want it to subscribe to a topic:
mqttClinet.subscribe("topic_name")

error is: 

my_project_folder/node_modules/aedes/lib/handlers/subscribe.js:116
    return done(null, null)
           ^

TypeError: done is not a function
    at SubState.storeSubscriptions (my_project_folder/node_modules/aedes/lib/handlers/subscribe.js:116:12)
    at work (my_project_folder/node_modules/fastfall/fall.js:103:23)
    at Aedes.aedes.authorizeSubscribe (my_project_folder/dist/index.js:137:9)
    at SubState.authorize (my_project_folder/node_modules/aedes/lib/handlers/subscribe.js:98:17)
    at Holder.work (my_project_folder/node_modules/fastfall/fall.js:105:23)
    at SubState.compiled (my_project_folder/node_modules/fastfall/fall.js:55:17)
    at SubscribeState.doSubscribe (my_project_folder/node_modules/aedes/lib/handlers/subscribe.js:89:16)
    at goResultsFunc (my_project_folder/node_modules/fastparallel/parallel.js:63:16)
    at Aedes.parallel [as _parallel] (my_project_folder/node_modules/fastparallel/parallel.js:33:9)
    at handleSubscribe (my_project_folder/node_modules/aedes/lib/handlers/subscribe.js:78:17)

**Comment by robertsLando** [comment]
@mcollina `storeSubscriptions` is called by `fastfall`, how is it possible that `callback` is not defined? Is that a bug on fastfall?

https://github.com/moscajs/aedes/blob/main/lib/handlers/subscribe.js#L11

https://github.com/moscajs/aedes/blob/main/lib/handlers/subscribe.js#L116

**Comment by robertsLando** [comment]
@deluxeroot could you create a repo that reproduces the issue?

**Comment by deluxeroot** [comment]
In aedes.authorizeSubscribe callback function had only one parameter and that was the problem. I added one more parameter and the error is gone.

**Comment by robertsLando** [comment]
> In aedes.authorizeSubscribe callback function had only one parameter and that was the problem. I added one more parameter and the error is gone.

That should have 3 parameters, `client, sub, done`
