### ISSUE TITLE
Client connects and disconnects immediately

### ISSUE THREAD

**Issue by automateAll** [moscajs/aedes#498]
I am writing some Integration tests between as JS app and Aedes server over websocket.
I have observed that, my test cases (involving 2 Paho-mqtt clients) are successfully able to **connect** to aedes broker, **publish** &**subscribe** the messages and also **close** the connection at the end when ran individually.
However, when ran  as a suite, only first test case runs fine but the 2nd test case tries to connect and the disconnects immediately. 

**Below is the output:**
```

.disconnecting
Client disconnected GroverMQTTClient
disconnecting
Client disconnected mqttTestClient
.Destroying broker
.Starting Broker....
websocket server listening on port 61614
.Given statement...
connecting to 127.0.0.1:61614 as GroverMQTTClient
new client GroverMQTTClient
Client disconnected GroverMQTTClient
Connection failed
client error GroverMQTTClient connection closed Error: connection closed
    at write (C:\spool\Sesame-St-Grover\node_modules\aedes\lib\write.js:16:47)
    at ClientPacketStatus.doConnack (C:\spool\Sesame-St-Grover\node_modules\aedes\lib\handlers\connect.js:217:3)
    at makeCallTwo (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:150:3)
    at release (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:138:7)
    at ClientPacketStatus.registerClient (C:\spool\Sesame-St-Grover\node_modules\aedes\lib\handlers\connect.js:211:3)
    at makeCallTwo (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:150:3)
    at release (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:138:7)
    at C:\spool\Sesame-St-Grover\node_modules\aedes\lib\handlers\connect.js:203:7
    at MemoryPersistence.delWill (C:\spool\Sesame-St-Grover\node_modules\aedes-persistence\persistence.js:312:3)
    at ClientPacketStatus.storeWill (C:\spool\Sesame-St-Grover\node_modules\aedes\lib\handlers\connect.js:196:29)
    at makeCallTwo (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:150:3)
    at SubscribeState.release [as finish] (C:\spool\Sesame-St-Grover\node_modules\fastseries\series.js:138:7)
    at ResultsHolder.release (C:\spool\Sesame-St-Grover\node_modules\fastparallel\parallel.js:183:12)
    at SubState.SingleCaller.release (C:\spool\Sesame-St-Grover\node_modules\fastparallel\parallel.js:157:17)
    at Immediate.work (C:\spool\Sesame-St-Grover\node_modules\fastfall\fall.js:121:25)
    at processImmediate (internal/timers.js:444:21)

```

**Aedes implementation:**
```
,
"use strict";
import ws from "websocket-stream";
import Aedes from "aedes";
import http from "http";

const httpServer = http.createServer();
const aedes = Aedes();
const wsPort = 61614;

export const startAedesServer = () => {
    ws.createServer({
        server: httpServer
    }, aedes.handle)

    httpServer.listen(wsPort, function () {
        console.log('websocket server listening on port', wsPort)
    })
};

aedes.on("publish", function (packet, client) {
    if (client) {
        console.log("message from client", client.id);
    }
});

aedes.on("subscribe", function (subscriptions, client) {
    if (client) {
        console.log("subscribe from client", subscriptions, client.id);
    }
});

aedes.on("client", function (client) {
    console.log("new client", client.id);
});

aedes.on("clientError", function (client, err) {
    console.log("client error", client.id, err.message, err.stack);
});

aedes.on("connectionError", function (client, err) {
    console.log("client error", client, err.message, err.stack);
    aedes.close();
});

aedes.on("clientDisconnect", function (client) {
    console.log("Client disconnected", client.id);
});


export const endAedesServer = () => {
    httpServer.close();
};

```

Is there something i am missing while trying to close the connections?

**Comment by automateAll** [comment]
Ok, i was able to fix it. I realized that i am supposed to close 2 connections:
1) Websocket connection
2) httpServer connection

something like this:
```
const httpServer = http.createServer();
const aedes = new Aedes();
const wsPort = 61614;
var websocketInstance;

export const startAedesServer = () => {

    websocketInstance = ws.createServer({ server: httpServer }, aedes.handle);

    httpServer.listen(wsPort, function () {
        console.log('websocket server listening on port', wsPort)
    })
};

export const endAedesServer = () => {
    websocketInstance.close();
    httpServer.close();
};
```

**Comment by automateAll** [comment]
I must say, Aedes is a great work. Kudos to the team :)

**Comment by robertsLando** [comment]
@automateAll Glad you fixed it :)

**Comment by demian85** [comment]
Why are you closing connections? I don't understand the purpose of it. Isn't it a long running server? why do you need to close connections?
I'm running into a similar issue, getting the following error:

```{"level":30,"time":1593734498523,"pid":8950,"hostname":"ip-10-10-15-180","name":"mqtt-broker","clientId":"lambda","msg":"Client connected","v":1}
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connection closed
    at write (/var/app/current/node_modules/aedes/lib/write.js:18:13)
    at writeQoS (/var/app/current/node_modules/aedes/lib/client.js:179:5)
    at Immediate.<anonymous> (/var/app/current/node_modules/aedes/lib/client.js:136:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
Emitted 'error' event on Transform instance at:
    at Transform.onerror (/var/app/current/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:311:20)
    at Transform.EventEmitter.emit (domain.js:482:12)
    at errorOrDestroy (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at onwriteError (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:430:5)
    at onwrite (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:450:11)
    at WritableState.onwrite (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:160:5)
    at Transform.afterTransform (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_transform.js:89:3)
    at processImmediate (internal/timers.js:458:21)
    at process.topLevelDomainCallback (domain.js:137:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mqtt-broker@1.0.0 start: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mqtt-broker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> mqtt-broker@1.0.0 start /var/app/current
> node build/index.js```

**Comment by robertsLando** [comment]
> Why are you closing connections? I don't understand the purpose of it. Isn't it a long running server? why do you need to close connections?

A test suite needs all connections to be closed in order to complete or it will hang. When a client connects to a broker there is a socket opened and that socket needs to be closed once the test is finished
