### ISSUE TITLE
Aedes closes after client disconnection

### ISSUE THREAD

**Issue by jaaambee** [moscajs/aedes#525]
Hi! I'm trying to use LWT to check the status of a IOT hardware. But when I disconnect my device and the broker sends the LWT "offline" message on "/event/deviceID/status" topic, I get the next error and the aedes client closes.

**/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/lib/cli.js:363
    logger.debug('ACK of %s received from client \x1b[33m%s\x1b[0m, broker %s', packet.topic, (client ? client.id : client), broker.id)
                                                                                       ^
TypeError: Cannot read property 'topic' of undefined
    at Aedes.<anonymous> (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/lib/cli.js:363:88)
    at Aedes.emit (events.js:315:20)
    at /Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/aedes/lib/handlers/puback.js:6:19
    at MemoryPersistence.outgoingClearMessageId (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/aedes-persistence/persistence.js:239:3)
    at handlePuback (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/aedes/lib/handlers/puback.js:5:15)
    at handle (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/aedes/lib/handlers/index.js:41:7)
    at Parser.enqueue (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/aedes/lib/client.js:350:5)
    at Parser.emit (events.js:315:20)
    at Parser._newPacket (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/mqtt-packet/parser.js:669:10)
    at Parser.parse (/Users/jaambee/.nvm/versions/node/v12.18.0/lib/node_modules/aedes-cli/node_modules/mqtt-packet/parser.js:41:41)**

I run aedes with the next command:

> aedes start --host 192.168.43.21 --protos tcp ws

Any help?

Thanks you!

**Comment by robertsLando** [comment]
Please update aedes-cli to larest version, this has been already fixed
