### ISSUE TITLE
[bug]Use the latest version

### ISSUE THREAD

**Issue by weiliudong** [moscajs/aedes#780]
After replacing with the latest version, the device is abnormally connected to the cluster.
"aedes": "^0.48.0"
"aedes-persistence-redis": "^9.0.1"
"mqemitter-redis": "^5.0.0"

4|mglink_mqtt  | TypeError: Cannot read properties of undefined (reading 'length')
4|mglink_mqtt  |     at validateTopic (/root/mglink_node/node_modules/aedes/lib/utils.js:6:21)
4|mglink_mqtt  |     at SubState.authorize (/root/mglink_node/node_modules/aedes/lib/handlers/subscribe.js:93:15)
4|mglink_mqtt  |     at Holder.work (/root/mglink_node/node_modules/fastfall/fall.js:105:23)
4|mglink_mqtt  |     at SubState.compiled (/root/mglink_node/node_modules/fastfall/fall.js:55:17)
4|mglink_mqtt  |     at SubscribeState.doSubscribe (/root/mglink_node/node_modules/aedes/lib/handlers/subscribe.js:89:16)
4|mglink_mqtt  |     at goResultsFunc (/root/mglink_node/node_modules/fastparallel/parallel.js:63:16)
4|mglink_mqtt  |     at Aedes.parallel [as _parallel] (/root/mglink_node/node_modules/fastparallel/parallel.js:33:9)
4|mglink_mqtt  |     at handleSubscribe (/root/mglink_node/node_modules/aedes/lib/handlers/subscribe.js:78:17)
4|mglink_mqtt  |     at ClientPacketStatus.restoreSubs (/root/mglink_node/node_modules/aedes/lib/handlers/connect.js:180:5)
4|mglink_mqtt  |     at makeCallTwo (/root/mglink_node/node_modules/fastseries/series.js:150:3)

help me

**Comment by weiliudong** [comment]
server linux version : Linux iZwz9d6oh1bh7ilukhile6Z 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by robertsLando** [comment]
@weiliudong What's the previous version you was using? Do you also know what's the subscrbie action that causes this?

**Comment by weiliudong** [comment]
@robertsLando 
The previous version was
"aedes": "^0.46.3"
"aedes-persistence-redis": "^8.0.1"
"mqemitter-redis": "^4.2.0"

**Comment by robertsLando** [comment]
Could you tell me what subscribe command throws tha?

**Comment by weiliudong** [comment]
@robertsLando It should be an exception when this method is called.
function authorize (sub, done) {
   const err = validateTopic(sub.topic, 'SUBSCRIBE')
   if (err) {
     return done(err)
   }
   const client = this.client
   client.broker.authorizeSubscribe(client, sub, done)
}

Compare the old version

This is a lot like theme permissions
authorizeSubscribe
The problem
but i'm not sure

**Comment by weiliudong** [comment]
Received, here is to determine where the caller is, find and send it to you for analysis

**Comment by weiliudong** [comment]
@robertsLando 
I found the problem here, it is the problem of your module configuration
"aedes": "^0.48.0",
  "aedes-persistence-redis": "^9.0.1",
When used together, the above-mentioned problems occur directly;

when I replace it with
"aedes": "^0.48.0",
  "aedes-persistence-redis": "^8.0.1",
fully working fine

Conclusion: The new version of "aedes": "^0.48.0" does not fit the new version of "aedes-persistence-redis": "^9.0.1"

Currently
"aedes": "^0.48.0" and "aedes-persistence-redis": "^8.0.1" will work.

This is the problem we are currently encountering with the upgrade module

Because it is a problem with aedes internal module adaptation, we can't confirm the specific problem for you, you have to investigate.

**Comment by robertsLando** [comment]
Could you give a try to 

```
"aedes": "^0.48.0",
"aedes-persistence-redis": "^9.0.0",
```

**Comment by weiliudong** [comment]
@robertsLando 
/aedes-main/lib/handlers/index.js

function handle (client, packet, done) {
  if (packet.cmd === 'connect') {
    if (client.connecting || client.connected) {
      // [MQTT-3.1.0-2]
      finish(client.conn, packet, done)
      return
    }
    console.log("handle (client, packet, done)===",client.id, packet)
    handleConnect(client, packet, done)
    return
  }
When the device is connected
handleConnect(client, packet, done)
method to process packets,

When the store restoreSubs method fires

console.log("arg.subs===",arg.subs)

function restoreSubs (arg, done) {
  if (arg.subs) {
    console.log("arg.subs===",arg.subs)
    handleSubscribe(this.client, { subscriptions: arg.subs }, true, done)
    arg.sessionPresent = !!arg.subs // cast to boolean, [MQTT-3.2.2-2]
    return
  }
  arg.sessionPresent = false // [MQTT-3.2.2-1], [MQTT-3.2.2-3]
  done()
}

new SubscribeState(client, packet, restore, done)

function SubscribeState (client, packet, restore, finish) {
  this.client = client
  this.packet = packet
  this.actions = restore ? restoreTopicActions : subscribeTopicActions
  this.finish = finish
  this.subState = []
}

This triggers subscribeTopicActions

const subscribeTopicActions = fastfall([
  authorize,
  storeSubscriptions,
  addSubs
])

Link trigger authorize, method

function authorize (sub, done) {
  console.log("sub, done===",sub, done,sub.topic)
  const err = validateTopic(sub.topic, 'SUBSCRIBE')
  if (err) {
    return done(err)
  }
  const client = this.client
  client.broker.authorizeSubscribe(client, sub, done)
}

when executing this
const err = validateTopic(sub.topic, 'SUBSCRIBE')

sub.topic is undefined

This is console.log("sub, done===",sub, done,sub.topic)
sub, done=== 49 [Function: work] undefined

At this time
function validateTopic (topic, message) {
   const end = topic.length - 1
   const endMinus = end - 1

topic===undefined
undefined has no length property, and the program dies as a result


This is an exception triggered when connecting, how can we avoid or fix it?

**Comment by weiliudong** [comment]
@robertsLando This is the packet content
enqueue (packet)=== Packet {
  cmd: 'connect',
  retain: false,
  qos: 0,
  dup: false,
  length: 99,
  topic: null,
  payload: null,
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: false,
  keepalive: 180,
  clientId: 'test',
  username: 'test',
  password: <Buffer 47 54 62 >
}

**Comment by robertsLando** [comment]
@weiliudong does that fixed your problem?

**Comment by rosenvivanov** [comment]
> Could you give a try to
> 
> ```
> "aedes": "^0.48.0",
> "aedes-persistence-redis": "^9.0.0",
> ```

It's the same error. I've tried with:
- "aedes-persistence-redis": "^9.0.1" and "^9.0.0"
-  "mqemitter-redis": "^5.0.0" and "^4.2.0"

/home/rosen/www/aedes-broker-tests/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

TypeError: Cannot read property 'length' of undefined
    at validateTopic (/home/aedes-broker-tests/node_modules/aedes/lib/utils.js:6:21)
    at SubState.authorize (/home/aedes-broker-tests/node_modules/aedes/lib/handlers/subscribe.js:93:15)
    at Holder.work (/home/aedes-broker-tests/node_modules/fastfall/fall.js:105:23)
    at SubState.compiled (/home/aedes-broker-tests/node_modules/fastfall/fall.js:55:17)
    at SubscribeState.doSubscribe (/home/aedes-broker-tests/node_modules/aedes/lib/handlers/subscribe.js:89:16)
    at goResultsFunc (/home/aedes-broker-tests/node_modules/fastparallel/parallel.js:63:16)
    at Aedes.parallel [as _parallel] (/home/aedes-broker-tests/node_modules/fastparallel/parallel.js:33:9)
    at handleSubscribe (/home/aedes-broker-tests/node_modules/aedes/lib/handlers/subscribe.js:78:17)
    at ClientPacketStatus.restoreSubs (/home/aedes-broker-tests/node_modules/aedes/lib/handlers/connect.js:180:5)
    at makeCallTwo (/home/aedes-broker-tests/node_modules/fastseries/series.js:150:3)

**Comment by robertsLando** [comment]
@rosenvivanov could you create a script to reproduce this error please?

**Comment by rosenvivanov** [comment]
> @rosenvivanov could you create a script to reproduce this error please?

Yes, but now I'm getting another issue.

/home/aedes-broker-tests/node_modules/qlobber/lib/qlobber.js:602
    const r = topic.split(this._separator);
                    ^

TypeError: Cannot read property 'split' of undefined
    at QlobberSub.Qlobber._split_words (/home/aedes-broker-tests/node_modules/qlobber/lib/qlobber.js:602:21)
    at QlobberSub.Qlobber._split (/home/aedes-broker-tests/node_modules/qlobber/lib/qlobber.js:624:18)
    at QlobberSub.Qlobber.remove (/home/aedes-broker-tests/node_modules/qlobber/lib/qlobber.js:669:35)
    at RedisPersistence._onMessage (/home/aedes-broker-tests/node_modules/aedes-cached-persistence/index.js:46:20)
    at goNoResultsArray (/home/aedes-broker-tests/node_modules/fastparallel/parallel.js:111:18)
    at MQEmitterRedis.parallel [as _parallel] (/home/aedes-broker-tests/node_modules/fastparallel/parallel.js:35:9)
    at MQEmitterRedis.MQEmitter._do (/home/aedes-broker-tests/node_modules/mqemitter/mqemitter.js:121:8)
    at MQEmitterRedis.emit (/home/aedes-broker-tests/node_modules/mqemitter/mqemitter.js:103:10)
    at handler (/home/aedes-broker-tests/node_modules/mqemitter-redis/mqemitter-redis.js:48:12)
    at EventEmitter.<anonymous> (/home/aedes-broker-tests/node_modules/mqemitter-redis/mqemitter-redis.js:58:5)

I'm testing with redis cluster mode. Look at the repo:

https://gitlab.com/rosen.ivanov/aedes-broker-tests

1. Run three aedes instances with: node broker.js, node broker.js 1 and node broker.js 2
2. Run clients.js script

**Comment by robertsLando** [comment]
ok thanks!

**Comment by rosenvivanov** [comment]
> ok thanks!

I've tested and I haven't managed to get the above error. We can consider that it has been something broken in the node modules.

But I noticed something other:

Event connectionError: **null**
Error: read ECONNRESET
 at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
 errno: -104,
 code: 'ECONNRESET',
 syscall: 'read'
}

This is printed by below event every 20-30 sec

`
aedes.on('connectionError', function (client, error) {
  console.log('Event connectionError: \x1b[31m' + (client ? client.id : 'undefined') + '\x1b[0m')
  console.log(error);
})
`

**Comment by robertsLando** [comment]
That error is emitted [here](https://github.com/moscajs/aedes/blob/b4e76882833d12866099ab4ba9afb3943919c712/lib/client.js#L208)

ECONNRESET error is emitted when:

> the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors.

**Comment by weiliudong** [comment]
@robertsLando It is normal for the device side to have jitter due to poor network connection, but as aedes, we should not interrupt the main process of the entire program for this reason, but throw the exception to the application layer for processing.

The production environment has already deployed a lot of aedes, and they dare not upgrade to the new version.

For this length exception, most of them should be attributable to protocol errors, resulting in aede not being able to get the topic, unable to parse the corresponding topic length, and causing the program to crash.

**Comment by weiliudong** [comment]
This is the part I made by downloading the source code of aedes and then modifying it so that the new version of aedes
"aedes": "^0.48.0",
"aedes-persistence-redis": "^9.1.0",
to work together

function handleSubscribe(client, packet, restore, done) {
    packet.subscriptions = replace(client, packet)// Subscribe while processing connection
    packet.subscriptions = packet.subscriptions.length === 1 ? packet.subscriptions : _dedupe(packet.subscriptions)
    client.broker._parallel(
        new SubscribeState(client, packet, restore, done), // what will be this in the functions
        doSubscribe, // function to call
        packet.subscriptions, // first argument of the function
        restore ? done : completeSubscribe // the function to be called when the parallel ends
    )

    function replace(client, packet) {
        const {id} = client
        const array = []
        const {subscriptions} = packet
        for (const item of subscriptions) {
            if (item === 49) {
                array.push({topic: `${id}/connect`, qos: 0})
            } else {
                array.push(item)
            }
        }
        return array
    }
}

**Comment by robertsLando** [comment]
> It is normal for the device side to have jitter due to poor network connection, but as aedes, we should not interrupt the main process of the entire program for this reason, but throw the exception to the application layer for processing.

Sure, what I don't understand is why this happens, I mean I know where the exception is thrown: https://github.com/moscajs/aedes/blob/main/lib/utils.js#L6

Because fixing that code takes 10 seconds but I have a feel the error could just be hidden in that way, topic should never be null

**Comment by robertsLando** [comment]
@weiliudong Please explain this:

```js
for (const item of subscriptions) {
            if (item === 49) {
                array.push({topic: `${id}/connect`, qos: 0})
            } else {
                array.push(item)
            }
        }
```

Why an item could be `49` ??

**Comment by weiliudong** [comment]
@robertsLando yes

**Comment by weiliudong** [comment]
We use the C code written by this connected module to connect to aedes, you can use this module to reproduce
https://mongoose.ws/tutorials/
![image](https://user-images.githubusercontent.com/24930918/199428262-7f4c7268-3428-4ae5-bac1-a5b75e0be936.png)
you can look here

**Comment by weiliudong** [comment]
@robertsLando 

@weiliudong Please explain this:

for (const item of subscriptions) {
            if (item === 49) {
                array.push({topic: `${id}/connect`, qos: 0})
            } else {
                array.push(item)
            }
        }
Why an item could be 49 ??
![image](https://user-images.githubusercontent.com/24930918/199430481-9ce8af5a-52fc-4060-936b-0acae6c9b828.png)

It seems that there is a problem with the action "connectActions" when connecting

**Comment by robertsLando** [comment]
Ok so that item is something fetched from redis subscriptions? I don't remember if the error goes away by downgrading aedes persistence redis or not. (be sure to clean up redis db when doingg a new test or some errors could be due to the previous versions)

**Comment by robertsLando** [comment]
> What is the client.broker._series method used for?

It uses [fast-series](https://www.npmjs.com/package/fastseries) module

**Comment by robertsLando** [comment]
So the error could be in redis `addSubscriptions` method: https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L113

Or `subscriptionsByClient` (used to fetch subscriptions to restore once a client connects): https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L194

Could you try to debug this to see if something is wrong there?

**Comment by weiliudong** [comment]
> remember

ok

**Comment by reijosirila** [comment]
> Or `subscriptionsByClient` (used to fetch subscriptions to restore once a [client connects ](https://github.com/moscajs/aedes/blob/main/lib/handlers/connect.js#L157) with clean flag set to false): https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L194

We have the same issue upgrading from 

    "aedes": "0.46.3",
    "aedes-persistence-redis": "8.0.1",

to

    "aedes": "0.48.0",
    "aedes-persistence-redis": "9.0.1", 

In our case it happens only with clients with clean flag false.

**Comment by robertsLando** [comment]
@reijosirila Pleaase check my previous comment: https://github.com/moscajs/aedes/issues/780#issuecomment-1299742571

I think the error is here: https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js#L194

It could have been introduced from: https://github.com/moscajs/aedes-persistence-redis/pull/96/files

In that version the clientId has been sanitized using `encodeURIComponent` function like you can see [here](https://github.com/moscajs/aedes-persistence-redis/pull/96/files#diff-58943acef9db8f8aea955bd46f71e484c4f318473dfdf1fb5f0a4aaecf789a9dR28)

That's why we also  bumped a major for that. Could you do some tests and check if that's the reason?

**Comment by reijosirila** [comment]
Added some debug before and after update: 

```shell
    #### hgetall? clientSubKey client:service-test
    #### hgetall? subs { 'device/id/+/#': '0' }
    #### hgetall? toReturn [ { topic: 'device/id/+/#', qos: 0 } ]
// after update
    ###hgetallBuffer clientSubKey(client.id)? client:service-test
    ### hgetallBuffer subs? { 'device/id/+/#': <Buffer 30> }
    ### hgetallBuffer toReturn? [ 48 ]
```

**Comment by robertsLando** [comment]
@reijosirila I have just published a patch that at least should prevent broker to crash. 

About the issue, I think the problem is that previously the subs where not encoded with msgpack, with version 9 the encode has been added so when decode is called it is called not with a string but with an object and that causes the issue. Could you submit a fix to aedes-persistence-redis?

**Comment by reijosirila** [comment]
Yep. Just finished checking `addSubscriptions` function and this is the case. I'll try to do PR.
