### ISSUE TITLE
Error: connection closed - 15k parallel connections [question]

### ISSUE THREAD

**Issue by rosenvivanov** [moscajs/aedes#784]
Error: connection closed
	at write (..../node_modules/aedes/lib/write.js:18:13)
	at SubscribeState.completeSubscribe (..../node_modules/aedes/lib/handlers/subscribe.js:189:5)
	at ResultsHolder.release (..../node_modules/fastparallel/parallel.js:183:12)
	at SubState.SingleCaller.release (..../node_modules/fastparallel/parallel.js:157:17)
	at Immediate.work (..../node_modules/fastfall/fall.js:121:25)
	at processImmediate (node:internal/timers:466:21)

If I try to connect over 10k connections at the same time, the error above occurs - and Aedes loops endlessly because the clients try to reconnect again and again, but the broker node isn't available at that time. I propose this is something related to the reading/writing into Redis, right? Would it be possible to set up some delay or some other way to prevent that loop?

**Comment by robertsLando** [comment]
What emitter and what persistence are you using?

**Comment by rosenvivanov** [comment]
> What emitter and what persistence are you using?

Both - Redis

**Comment by robertsLando** [comment]
Does using mongo leads to the same? That error happens when for some reason client is disconnected, is the authentication failing? Does it have the same client id of another client?

**Comment by rosenvivanov** [comment]
> Does using mongo leads to the same? That error happens when for some reason client is disconnected, is the authentication failing? Does it have the same client id of another client?

I haven't checked with mongo, but it happens every time when I try bulk reconnect. If I try with the smaller portion, e.g. 2000 clients - it works.
As Redis is a single-thread process, I see that the CPU grows up to 100% (with 10-15k clients) and then probably the broker closes connections.

**Comment by robertsLando** [comment]
> As Redis is a single-thread process, I see that the CPU grows up to 100% (with 10-15k clients) and then probably the broker closes connections.

Could be, BTW what should aedes do in this case? The reconnect should be delayed on client side not aedes

**Comment by rosenvivanov** [comment]
Could it be a solution decreasing of concurrency property?

**Comment by robertsLando** [comment]
> Could it be a solution decreasing of concurrency property?

**Increasing** concurrency could be an option, not decreasing

**Comment by rosenvivanov** [comment]
I've set 20k. I'll test with 50k. I'll also test with mongo and will let you know.
I tried with redis cluster, but it works only when cluster is on localhost. On remote, aedes can't connect. Do you know something about that?

**Comment by robertsLando** [comment]
For persistence it needs this I think: https://github.com/moscajs/aedes-persistence-redis/issues/85
For mqemitter I dunno, you should check yourself

**Comment by rosenvivanov** [comment]
OK, thanks. I'll analyze the behavior with mongo, with increased concurrency and cluster. I'll post the results in the next couple of days.

**Comment by robertsLando** [comment]
> If we use architecture with multiple aedes instances, which share persistence ... when some of the clients break the connection and reconnect again and connect to another node, the previous node remembers that client and when we try to communicate with the client, the old node throws an exception:

Hi @rosenvivanov, it looks this is an issue and there may be something to clean on aedes state, maybe we are not cleaning `aedes.clients` object, could you give that a check? 

It's an object where keys are clientIds and values are clients class:

Check:
https://github.com/moscajs/aedes/blob/main/aedes.js#L310
https://github.com/moscajs/aedes/blob/main/lib/client.js#L326

Or I bet we are not cleaning subscriptions once client disconnects. When it subscribes we call [broker.subscribe ](https://github.com/moscajs/aedes/blob/main/lib/handlers/subscribe.js#L160) that essentially calls [mq.on](https://github.com/moscajs/aedes/blob/main/aedes.js#L281) method, we should also call broker.unsubscribe. 

We actually call `handleUnsubscribe` [here](https://github.com/moscajs/aedes/blob/main/lib/client.js#L294) but it may fail for some reason and in that case broker.unsubscribe is never called.

Could you give this a check

**Comment by robertsLando** [comment]
Fixed?

**Comment by robertsLando** [comment]
Ok
