### ISSUE TITLE
Frequent service clientError Error: invalid status code: 12592

### ISSUE THREAD

**Issue by junthink** [moscajs/aedes#946]
This is the stack

clientError Error: invalid status code: 12592
    at Receiver.controlMessage (/data/www/prod/mqtt-server/node_modules/ws/lib/Receiver.js:414:22)
    at Receiver.getData (/data/www/prod/mqtt-server/node_modules/ws/lib/Receiver.js:325:12)
    at Receiver.startLoop (/data/www/prod/mqtt-server/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/data/www/prod/mqtt-server/node_modules/ws/lib/Receiver.js:139:10)
    at Socket.<anonymous> (/data/www/prod/mqtt-server/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  type: 'error',
  target: WebSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    readyState: 3,
    bytesReceived: 587,
    extensions: null,
    protocol: 'mqtt',
    _binaryType: 'nodebuffer',
    _finalize: [Function: bound finalize] { __ultron: 356 },
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _finalized: true,
    _closeCode: 1002,
    _receiver: null,
    _sender: null,
    _socket: null,
    _ultron: null,
    protocolVersion: 13,
    _maxPayload: 104857600,
    _isServer: true,
    [Symbol(kCapture)]: false
  }
}

**Comment by robertsLando** [comment]
It seems to me this error comes from ws module and not aedes
